version: '3'

services:
  # Node.js application
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - xray_daemon
    environment:
      AWS_XRAY_DAEMON_ADDRESS: xray_daemon:2000

  # AWS X-Ray Daemon
  #https://repost.aws/questions/QUr6JJxyeLRUK5M4tadg944w/x-ray-in-ecs-get-instance-id-metadata-failed
  xray_daemon:
    image: amazon/aws-xray-daemon:3.x
    ports:
      - "2000:2000/udp"
    env_file:
      - variables.env

networks:
  custom_network: 
    driver: bridge   

# Add any additional configurations or volumes as needed
#Some important debugging commands:
#Get Ip address of the container_app: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' node_app
# docker exec {container_id} {command}
# docker exec node_app ls

#with user-defined bridge network you can also use the DNS in the docker container.
#docker exec node_app curl xray_daemon

#default bridge driver is not recommended for production use

