name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      env_var: ${{ vars.ENV_CONTEXT_VAR }}
      DOCKER_USERNAME: ${{ vars.YOUR_DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.YOUR_DOCKERHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag iluvyou3000/xray_instrumented_app:$(date +%s)
        docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD 
        docker push iluvyou3000/xray_instrumented_app:${{ github.run_id }}

