name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: YOUR_DOCKERHUB_USERNAME
      DOCKER_PASSWORD: ${{ secrets.YOUR_DOCKERHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag iluvyou3000/xray_instrumented_app:$(date +%s)
        docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD registry-index.docker.io
        docker push registry-index.docker.io/iluvyou3000/xray_instrumented_app:${{ github.run_id }}

