name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "$GITHUB_CONTEXT"
            
      - name: Dump Secret Context
        env:
          SECRET_CONTEXT: ${{ toJson(secrets) }}
        run: |
          echo "SECRET_CONTEXT"
      
      - name: Dump Local Env Contest
        run: |
          echo "ENV_CONTEXT: ${{ toJson(env) }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          username: "$DOCKERHUB_USERNAME"
          password: "$DOCKERHUB_PASSWORD"
          ecr: false

      - name: Build Docker Image
        shell: bash
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/xray_instrumented_app:latest
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xray_instrumented_app:latest
