name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: YOUR_DOCKERHUB_USERNAME
      DOCKER_PASSWORD: ${{ secrets.YOUR_DOCKERHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        docker login -u YOUR_DOCKERHUB_USERNAME -p ${{ secrets.YOUR_DOCKERHUB_TOKEN }} registry-index.docker.io
        docker push registry-index.docker.io/my-image-name:${{ github.run_id }}

